version: "3.7"

services:
    n8n:
        build:
            context: .
            args:
                - SUDO_PASSWORD=${SUDO_PASSWORD}

        container_name: n8n
        restart: unless-stopped
        ports:
            - "5678:5678"

        environment:
            - N8N_PROTOCOL=https
            - N8N_HOST=${N8N_HOST_URL}
            - VUE_APP_URL_BASE_API=https://${N8N_HOST_URL}/
            - WEBHOOK_URL=https://${N8N_HOST_URL}/
            - WEBHOOK_TUNNEL_URL=https://${N8N_HOST_URL}/
            - GENERIC_TIMEZONE=${TIMEZONE}
            - TZ=${TIMEZONE}
            - N8N_RUNNERS_ENABLED=true
            - SUDO_PASSWORD=${SUDO_PASSWORD}

        volumes:
            - n8n_data:/home/node/.n8n

        networks:
            - default-network

    whatsapp:
        image: aldinokemal2104/go-whatsapp-web-multidevice
        container_name: whatsapp
        restart: always
        ports:
            - "3000:3000"
        environment:
            - APP_AUTOREPLY_MESSAGE=${WHATSAPP_AUTO_REPLY}
            - APP_WEBHOOK_URL=${WHATSAPP_WEBHOOK}
            - APP_WEBHOOK_SECRET=${WHATSAPP_WEBHOOK_SECRET}
        volumes:
            - whatsapp:/app/storages
        networks:
            - default-network

volumes:
    n8n_data:
        external: true
    whatsapp:
        external: true

networks:
    default-network:
        external: true
