version: "3.7"

services:
    n8n:
        build:
            context: .
            args:
                # This securely passes the password to the Dockerfile during the build
                - SUDO_PASSWORD=${SUDO_PASSWORD}

        container_name: n8n2
        restart: unless-stopped
        ports:
            - "5678:5678"

        environment:
            # All your other environment variables
            - N8N_PROTOCOL=https
            - N8N_HOST=${N8N_HOST_URL}
            - VUE_APP_URL_BASE_API=https://${N8N_HOST_URL}/
            - WEBHOOK_URL=https://${N8N_HOST_URL}/
            - WEBHOOK_TUNNEL_URL=https://${N8N_HOST_URL}/
            - GENERIC_TIMEZONE=${TIMEZONE}
            - TZ=${TIMEZONE}
            - N8N_RUNNERS_ENABLED=true
            # This makes the password available inside the running container for your workflows
            - SUDO_PASSWORD=${SUDO_PASSWORD}

        volumes:
            - n8n_data:/home/node/.n8n

        networks:
            - default-network

volumes:
    n8n_data:

networks:
    default-network:
        external: true
